name: login_home
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/img/icon/
    - assets/img/logo/
    - assets/img/photo/
  
  fonts:
    - family: Lato
      fonts:
        # - asset: fonts/Lato-Thin.ttf
        #   weight: 100
        # - asset: fonts/Lato-ThinItalic.ttf
        #   weight: 100
        #   style: italic
        # - asset: fonts/Lato-Light.ttf
        #   weight: 300
        # - asset: fonts/Lato-LightItalic.ttf
        #   weight: 300
        #   style: italic
        - asset: fonts/Lato-Regular.ttf
          weight: 400
        # - asset: fonts/Lato-Italic.ttf
        #   weight: 400
          style: italic
        - asset: fonts/Lato-Bold.ttf
          weight: 700
        # - asset: fonts/Lato-BoldItalic.ttf
        #   weight: 700
        #   style: italic
        # - asset: fonts/Lato-Black.ttf
        #   weight: 900
        # - asset: fonts/Lato-BlackItalic.ttf
        #   style: italic
        #   weight: 900
